### ISSUE TITLE
Unable to locate element

### ISSUE THREAD

**Issue by 1947261582** [veryepicsalad/memrise-bot#1]
When i try to choose the firefox option this pops up
Traceback (most recent call last):
  File "memrise.py", line 163, in <module>
  File "memrise.py", line 22, in logIn
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 496, in find_element_by_name
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [name="username"]

[13404] Failed to execute script memrise
and for chrome it just instantly crashes. Could this be fixed please?

**Comment by s-alad** [comment]
Ok so a thing with this bot is that u have to replace the chrome and geck driver every time they get updated so try doing that cheif

**Comment by s-alad** [comment]
Also make sure ur getting the correct link for it, heres a sample link: https://app.memrise.com/course/2086/the-450-most-common-french-verbs/1/garden/learn/?source_element=level_details_session&source_screen=level_details

**Comment by s-alad** [comment]
To be honest Idk if this still works cuz the site got revamped and I made this around 8 months ago so IDK if it will work.

**Comment by 1947261582** [comment]
I'll try replacing the chrome driver and whatnot. And it's fine. Thank you so much for answering me!
________________________________

**Comment by 1947261582** [comment]
I have also realized I have been using the link to the lesson itself instead of the link that appears once you start learning. Basically I've been using this https://app.memrise.com/course/2086/the-450-most-common-french-verbs/1/ instead of https://app.memrise.com/course/2086/the-450-most-common-french-verbs/1/garden/learn/?source_element=level_details_session&source_screen=level_details so could that be the problem?
[https://static.memrise.com/img/400sqf/from/uploads/course_photos/drapeau5.png]<https://app.memrise.com/course/2086/the-450-most-common-french-verbs/1/>
Level 1 - 1 - 15 - The 450 Most Common French Verbs - Memrise<https://app.memrise.com/course/2086/the-450-most-common-french-verbs/1/>
French verbs in English. Practise and improve your French grammar, listening, speaking, reading and vocabulary. 1 - 15.
app.memrise.com

________________________________

**Comment by 1947261582** [comment]
Updated chromedriver and gecko and now i get this for both chrome and firefox 
DevTools listening on ws://127.0.0.1:64044/devtools/browser/3add795c-d801-49d0-ad61-c37363e368ad
Traceback (most recent call last):
  File "memrise.py", line 163, in <module>
  File "memrise.py", line 24, in logIn
IndexError: list index out of range
[5752] Failed to execute script memrise
If you can't fix it it's fine but do you know what is causing this?
